apiVersion: v1
kind: Pod
metadata:
  name: addipi
spec:
  containers:
  - name: queue-service
    image: addipi/queue-service
    imagePullPolicy: IfNotPresent
    envFrom:
      - secretRef:
          name: addipi-env
  
  - name: auth-service
    image: addipi/auth-service
    imagePullPolicy: IfNotPresent
    envFrom:
      - secretRef:
          name: addipi-env