version: '3.9'

services:
  files:
    image: ${FILES_IMAGE:-ghcr.io/AddiPii/AddiPi-Files-Service:latest}
    env_file:
      - .env
    ports:
      - "${FILES_PORT:-5000}:5000"
    restart: unless-stopped
    networks:
      - addipi-network

  queue:
    image: ${QUEUE_IMAGE:-ghcr.io/AddiPii/AddiPi-Queue-Service:latest}
    env_file:
      - .env
    depends_on:
      - auth
    ports:
      - "${QUEUE_PORT:-3070}:3070"
    restart: unless-stopped
    networks:
      - addipi-network

  auth:
    image: ${AUTH_IMAGE:-ghcr.io/AddiPii/AddiPi-Auth-Service:latest}
    env_file:
      - .env
    ports:
      - "${AUTH_PORT:-3001}:3001"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3001/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - addipi-network

  printer:
    image: ${PRINTER_IMAGE:-ghcr.io/AddiPii/AddiPi-Printer-Service:latest}
    env_file:
      - .env
    depends_on:
      - queue
      - auth
    ports:
      - "${PRINTER_PORT:-3050}:3050"
    restart: unless-stopped
    networks:
      - addipi-network

  watchtower:
    image: containrrr/watchtower:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/ubuntu/.docker/config.json:/config.json:ro
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_POLL_INTERVAL=3600
    restart: unless-stopped

  user:
    image: ${USER_IMAGE:-ghcr.io/AddiPii/AddiPi-User-Service:latest}
    env_file:
      - .env
    depends_on:
      - auth
    ports:
      - "${USER_PORT:-3002}:3002"
    restart: unless-stopped
    networks:
      - addipi-network

  # video:
  #   image: ${VIDEO_IMAGE:-ghcr.io/AddiPii/AddiPi-Video-Service:latest}
  #   env_file:
  #     - .env
  #   ports:
  #     - "${VIDEO_PORT:-3003}:3003"
  #   restart: unless-stopped

networks:
  addipi-network:
    name: addipi-network
